/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vérifier la clé API
         * @description Renvoie l'identifiant du marketplace résolu depuis la clé fournie. Utilisez cet endpoint pour valider votre clé de bout en bout.
         */
        get: operations["ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lister les produits
         * @description Renvoie les produits du marchand (paginés). Par défaut, seuls les produits activés sont retournés — passez `includeDisabled=true` pour inclure également les brouillons.
         */
        get: operations["listProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products/{publicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Récupérer un produit par son identifiant public
         * @description Renvoie un produit unique (avec variations, combinaisons et galerie). Passez `includeDisabled=true` pour résoudre également les brouillons.
         */
        get: operations["getProductByPublicId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products/by-slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Récupérer un produit par son slug
         * @description Renvoie un produit unique recherché par son slug URL-friendly. Passez `includeDisabled=true` pour résoudre également les brouillons.
         */
        get: operations["getProductBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lister les collections
         * @description Renvoie les collections du marchand (paginées). Supporte le tri et la recherche par nom.
         */
        get: operations["listCollections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/collections/{publicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Récupérer une collection par son identifiant public */
        get: operations["getCollectionByPublicId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/collections/by-slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Récupérer une collection par son slug */
        get: operations["getCollectionBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lister les commandes
         * @description Renvoie les commandes du marchand (paniers payés) paginées. Supporte la recherche sur le `publicId` de commande, la référence de paiement et les données client.
         */
        get: operations["listOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{publicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Récupérer une commande par son identifiant public
         * @description Renvoie le détail d'une commande (items, totaux, paiement, livraison).
         */
        get: operations["getOrderByPublicId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{publicId}/invoice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Télécharger la facture (PDF)
         * @description Renvoie la facture de la commande au format PDF (`application/pdf`). Renvoie 404 si aucune facture n'a encore été générée.
         */
        get: operations["getOrderInvoice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/carts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lister les paniers
         * @description Renvoie les paniers du marchand (paginés). Les paniers `DRAFT` sont réservés à un usage interne et ne sont jamais exposés.
         */
        get: operations["listCarts"];
        put?: never;
        /**
         * Créer un panier et initier le paiement
         * @description Crée un panier en `PENDING_PAYMENT` avec le client / les items / la livraison fournis, génère une ligne de paiement et demande une URL de checkout au provider de paiement. Si l'appel provider échoue, le panier est conservé et un `502 PAYMENT_INIT_FAILED` est retourné — relancez via `POST /v1/carts/{publicId}/pay`.
         */
        post: operations["createCart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/carts/{publicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Récupérer un panier par son identifiant public
         * @description Renvoie le détail d'un panier (items, totaux, livraison).
         */
        get: operations["getCartByPublicId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/carts/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculer les totaux d'un panier sans le persister
         * @description Prévisualisation sans état. Valide les items, la zone de livraison et la configuration split, puis renvoie les totaux finaux. Aucun panier n'est créé.
         */
        post: operations["previewCart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/carts/{publicId}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Relancer l'initialisation du paiement d'un panier existant
         * @description À utiliser uniquement lorsque l'appel précédent à `POST /v1/carts` a renvoyé `502 PAYMENT_INIT_FAILED` — c'est-à-dire que le panier est en `PENDING_PAYMENT` avec une ligne de paiement en attente. Re-sollicite le provider de paiement avec la même référence.
         */
        post: operations["retryCartPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Enveloppe de réponse standard pour une ressource unique. */
        DevApiSuccessEnvelopeDto: {
            /** @example true */
            success: boolean;
            /** @description Charge utile de la réponse. */
            data: Record<string, never>;
        };
        /** @description Enveloppe de réponse standard pour une collection paginée. Le header `Content-Range` accompagne toujours cette réponse. */
        DevApiPaginatedEnvelopeDto: {
            /** @example true */
            success: boolean;
            /** @description Tableau d'éléments pour la page courante. */
            data: Record<string, never>[];
            /**
             * @description Nombre total de lignes correspondant à la requête.
             * @example 42
             */
            total: number;
            /**
             * @description Index (1-based) de la première ligne renvoyée.
             * @example 1
             */
            start: number;
            /**
             * @description Index (1-based) de la dernière ligne renvoyée.
             * @example 10
             */
            end: number;
        };
        /** @description Enveloppe d'erreur standard. Le champ `errors` (optionnel) détaille les violations par champ pour les erreurs de validation. */
        DevApiErrorEnvelopeDto: {
            /** @example false */
            success: boolean;
            /**
             * @description Code d'erreur machine-readable. Voir la page Ressources › Erreurs pour la liste complète.
             * @example PRODUCT_NOT_FOUND
             */
            code: string;
            /**
             * @description Message lisible par un humain (français).
             * @example Le produit n'a pas été trouvé
             */
            message: string;
            /** @description Détail des violations par champ (uniquement pour les erreurs de validation). */
            errors?: {
                [key: string]: string[];
            };
            /** @description Contexte additionnel optionnel (ex. `cartPublicId` sur `PAYMENT_INIT_FAILED`). */
            data?: Record<string, never>;
        };
        DevApiCheckoutItemDto: {
            /** @example PRD-XPK39ZQA01 */
            publicProductId: string;
            /** @example 2 */
            quantity: number;
            /**
             * @description Identifiant public de la combinaison (SKU) si le produit a des variations.
             * @example COMB-ABC123
             */
            combinationPublicId?: string;
        };
        DevApiCheckoutDeliveryDto: {
            /**
             * @example DELIVERY
             * @enum {string}
             */
            deliveryType: "DELIVERY" | "PICKUP";
            /**
             * @description Requis lorsque `deliveryType = DELIVERY`.
             * @example 11
             */
            deliveryAreaId?: number;
        };
        DevApiCheckoutCustomerDto: {
            /** @example Jean */
            firstName: string;
            /** @example Kouassi */
            lastName: string;
            /**
             * Format: email
             * @example jean@example.com
             */
            email: string;
            /** @example +225 07 12 34 56 78 */
            phone: string;
        };
        DevApiCheckoutPreviewDto: {
            items: components["schemas"]["DevApiCheckoutItemDto"][];
            delivery: components["schemas"]["DevApiCheckoutDeliveryDto"];
            /**
             * @description Modes de paiement actuellement exposés par la Developer API.
             * @example external_wallet
             * @enum {string}
             */
            paymentMethod: "external_wallet" | "split_payment";
        };
        DevApiCheckoutCreateDto: {
            customer: components["schemas"]["DevApiCheckoutCustomerDto"];
            items: components["schemas"]["DevApiCheckoutItemDto"][];
            delivery: components["schemas"]["DevApiCheckoutDeliveryDto"];
            /**
             * @example external_wallet
             * @enum {string}
             */
            paymentMethod: "external_wallet" | "split_payment";
            /**
             * Format: uri
             * @description URL HTTPS vers laquelle le client est redirigé après le checkout. Doit obligatoirement être en HTTPS.
             * @example https://my-shop.com/after-checkout
             */
            returnUrl: string;
            /** @example Appeler 30 min avant */
            additionalDetails?: string;
            /**
             * @description Charge JSON libre renvoyée telle quelle dans toutes les réponses panier / commande. Utilisez-la pour rattacher vos propres identifiants (ex. `internalOrderId`).
             * @example {
             *       "internalOrderId": "ORD-12345",
             *       "source": "mobile-app"
             *     }
             */
            meta?: Record<string, never>;
        };
        DevApiCheckoutRetryPayDto: {
            /**
             * Format: uri
             * @example https://my-shop.com/after-checkout
             */
            returnUrl: string;
        };
    };
    responses: {
        /** @description Clé API manquante ou invalide */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
            };
        };
        /** @description Requête invalide (validation du body ou de la query) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "code": "BAD_REQUEST",
                 *       "message": "La requête est invalide",
                 *       "errors": {
                 *         "items": [
                 *           "doit contenir au moins 1 élément"
                 *         ]
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
            };
        };
        /** @description Ressource introuvable */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "code": "NOT_FOUND",
                 *       "message": "Ressource introuvable"
                 *     }
                 */
                "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
            };
        };
        /** @description Produit introuvable */
        ProductNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "code": "PRODUCT_NOT_FOUND",
                 *       "message": "Le produit n'a pas été trouvé"
                 *     }
                 */
                "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
            };
        };
        /** @description Panier introuvable */
        CartNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "code": "CART_NOT_FOUND",
                 *       "message": "Le panier n'a pas été trouvé"
                 *     }
                 */
                "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
            };
        };
        /** @description Le panier n'est plus dans un état autorisant un retry */
        CartNotRetryable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "code": "CART_NOT_RETRYABLE",
                 *       "message": "Ce panier n'est plus en attente de paiement"
                 *     }
                 */
                "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
            };
        };
        /** @description Une dépendance du checkout est introuvable (produit, combinaison ou zone de livraison) */
        CheckoutNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
            };
        };
        /** @description Stock insuffisant pour un ou plusieurs items */
        InsufficientStock: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "code": "INSUFFICIENT_STOCK",
                 *       "message": "Le stock est insuffisant",
                 *       "errors": {
                 *         "PRD-XPK39ZQA01": [
                 *           "stock disponible : 1, demandé : 2"
                 *         ]
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
            };
        };
        /** @description Limite de débit dépassée. Consultez le header `Retry-After` (secondes). */
        RateLimited: {
            headers: {
                /** @description Nombre de secondes à attendre avant de réessayer. */
                "Retry-After"?: number;
                /** @description Limite de la fenêtre courante. */
                "X-RateLimit-Limit"?: number;
                /** @description Requêtes restantes dans la fenêtre. */
                "X-RateLimit-Remaining"?: number;
                /** @description Timestamp Unix de réinitialisation de la fenêtre. */
                "X-RateLimit-Reset"?: number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "code": "RATE_LIMITED",
                 *       "message": "Trop de requêtes, veuillez patienter"
                 *     }
                 */
                "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
            };
        };
        /** @description Le provider de paiement n'a pas pu être joint. Le panier est conservé — relancez via `POST /v1/carts/{publicId}/pay`. */
        PaymentInitFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "code": "PAYMENT_INIT_FAILED",
                 *       "message": "L'initialisation du paiement a échoué, réessayez via /pay",
                 *       "data": {
                 *         "cartPublicId": "CART-XPK39ZQA01"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
            };
        };
    };
    parameters: {
        /** @description Numéro de page (≥ 1). */
        Page: number;
        /** @description Taille de page (bornée par la config plateforme, ~100 max). */
        PerPage: number;
        /** @description Sens de tri. */
        Order: "asc" | "desc";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Clé valide */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": true,
                     *       "data": {
                     *         "marketplaceId": 42,
                     *         "timestamp": "2026-05-28T10:15:00.000Z"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["DevApiSuccessEnvelopeDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    listProducts: {
        parameters: {
            query?: {
                /** @description Numéro de page (≥ 1). */
                page?: components["parameters"]["Page"];
                /** @description Taille de page (bornée par la config plateforme, ~100 max). */
                per_page?: components["parameters"]["PerPage"];
                /** @description Colonne de tri. */
                _sort?: "id" | "name" | "price" | "createdAt";
                /** @description Sens de tri. */
                _order?: components["parameters"]["Order"];
                /** @description Recherche plein-texte sur le nom du produit (3 caractères minimum). */
                search?: string;
                /** @description Filtrer par slug de collection. */
                collection?: string;
                /** @description Inclure les variations et combinaisons (SKU) dans la réponse. */
                includeVariations?: boolean;
                /** @description Inclure les produits désactivés (brouillons). Par défaut, seuls les produits activés sont retournés. */
                includeDisabled?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste paginée de produits */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiPaginatedEnvelopeDto"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    getProductByPublicId: {
        parameters: {
            query?: {
                /** @description Permet de résoudre un produit désactivé (brouillon). */
                includeDisabled?: boolean;
            };
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Produit trouvé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiSuccessEnvelopeDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["ProductNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    getProductBySlug: {
        parameters: {
            query?: {
                /** @description Permet de résoudre un produit désactivé (brouillon). */
                includeDisabled?: boolean;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Produit trouvé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiSuccessEnvelopeDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["ProductNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    listCollections: {
        parameters: {
            query?: {
                /** @description Numéro de page (≥ 1). */
                page?: components["parameters"]["Page"];
                /** @description Taille de page (bornée par la config plateforme, ~100 max). */
                per_page?: components["parameters"]["PerPage"];
                /** @description Colonne de tri. */
                _sort?: "id" | "name" | "createdAt";
                /** @description Sens de tri. */
                _order?: components["parameters"]["Order"];
                /** @description Recherche plein-texte sur le nom de la collection (3 caractères minimum). */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste paginée de collections */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiPaginatedEnvelopeDto"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    getCollectionByPublicId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Collection trouvée */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiSuccessEnvelopeDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    getCollectionBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Collection trouvée */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiSuccessEnvelopeDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    listOrders: {
        parameters: {
            query?: {
                /** @description Numéro de page (≥ 1). */
                page?: components["parameters"]["Page"];
                /** @description Taille de page (bornée par la config plateforme, ~100 max). */
                per_page?: components["parameters"]["PerPage"];
                /** @description Colonne de tri. */
                _sort?: "id" | "createdAt" | "amount";
                /** @description Sens de tri. */
                _order?: components["parameters"]["Order"];
                /** @description Recherche plein-texte sur le `publicId` de commande, la référence de paiement ou les infos client. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste paginée de commandes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiPaginatedEnvelopeDto"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    getOrderByPublicId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Commande trouvée */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiSuccessEnvelopeDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    getOrderInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flux PDF de la facture */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    listCarts: {
        parameters: {
            query?: {
                /** @description Numéro de page (≥ 1). */
                page?: components["parameters"]["Page"];
                /** @description Taille de page (bornée par la config plateforme, ~100 max). */
                per_page?: components["parameters"]["PerPage"];
                /** @description Colonne de tri. */
                _sort?: "id" | "createdAt";
                /** @description Sens de tri. */
                _order?: components["parameters"]["Order"];
                /** @description Recherche plein-texte sur le `publicId` de panier ou les infos client. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste paginée de paniers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiPaginatedEnvelopeDto"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    createCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevApiCheckoutCreateDto"];
            };
        };
        responses: {
            /** @description Panier créé, URL de checkout dans `data.checkoutUrl` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiSuccessEnvelopeDto"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["CheckoutNotFound"];
            422: components["responses"]["InsufficientStock"];
            429: components["responses"]["RateLimited"];
            502: components["responses"]["PaymentInitFailed"];
        };
    };
    getCartByPublicId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Panier trouvé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiSuccessEnvelopeDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["CartNotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    previewCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevApiCheckoutPreviewDto"];
            };
        };
        responses: {
            /** @description Totaux calculés */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiSuccessEnvelopeDto"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["CheckoutNotFound"];
            422: components["responses"]["InsufficientStock"];
            429: components["responses"]["RateLimited"];
        };
    };
    retryCartPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevApiCheckoutRetryPayDto"];
            };
        };
        responses: {
            /** @description Nouvelle URL de checkout dans `data.checkoutUrl` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiSuccessEnvelopeDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["CartNotFound"];
            409: components["responses"]["CartNotRetryable"];
            429: components["responses"]["RateLimited"];
            502: components["responses"]["PaymentInitFailed"];
        };
    };
}
