/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Authenticated ping
         * @description Returns the marketplace id resolved from the provided API key. Use it to verify that your key works end-to-end.
         */
        get: operations["DevApiPingController_ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List products
         * @description Returns the marchant's products (paginated). By default only enabled products are returned — set `includeDisabled=true` to also return drafts.
         */
        get: operations["ProductsDevApiController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products/{publicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a product by its public id
         * @description Returns a single product (with variations, combinations and gallery). Set `includeDisabled=true` to also resolve drafts.
         */
        get: operations["ProductsDevApiController_getByPublicId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products/by-slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a product by slug
         * @description Returns a single product looked up by its URL-friendly slug. Set `includeDisabled=true` to also resolve drafts.
         */
        get: operations["ProductsDevApiController_getBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List collections
         * @description Returns the marchant's collections (paginated). Supports sorting and search by name.
         */
        get: operations["CollectionsDevApiController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/collections/{publicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a collection by its public id */
        get: operations["CollectionsDevApiController_getByPublicId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/collections/by-slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a collection by slug */
        get: operations["CollectionsDevApiController_getBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List orders
         * @description Returns the merchant's orders (paid carts) paginated. Supports search on order publicId, payment reference and customer data.
         */
        get: operations["OrdersDevApiController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{publicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an order by its public id
         * @description Returns the order detail (items, totals, payment, delivery).
         */
        get: operations["OrdersDevApiController_getByPublicId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{publicId}/invoice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download the order invoice (PDF)
         * @description Streams the order invoice as a PDF. Returns 404 if no invoice has been generated yet.
         */
        get: operations["OrdersDevApiController_getInvoice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/carts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List carts
         * @description Returns the merchant's carts (paginated). DRAFT carts are reserved for internal usage and are never exposed.
         */
        get: operations["CartsDevApiController_list"];
        put?: never;
        /**
         * Create a cart and initiate its payment in one call
         * @description Creates a PENDING_PAYMENT cart with the given customer/items/delivery, generates a payment row, and asks the payment provider for a checkout URL. If the provider call fails, the cart is kept and a 502 PAYMENT_INIT_FAILED is returned — retry via POST /v1/carts/{publicId}/pay.
         */
        post: operations["CheckoutDevApiController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/carts/{publicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a cart by its public id
         * @description Returns the cart detail (items, totals, delivery info).
         */
        get: operations["CartsDevApiController_getByPublicId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/carts/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compute cart totals without persisting anything
         * @description Stateless preview. Validates items + delivery area + split config and returns final totals. No cart row is created.
         */
        post: operations["CheckoutDevApiController_preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/carts/{publicId}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry payment initialization for an existing cart
         * @description Only usable when the previous POST /v1/carts call returned 502 PAYMENT_INIT_FAILED — i.e. the cart is in PENDING_PAYMENT with a pending payment row. Re-calls the payment provider with the same payment reference.
         */
        post: operations["CheckoutDevApiController_retryPay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/delivery-areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List delivery areas
         * @description Returns every delivery area configured for the marketplace. Use an area `id` as `delivery.deliveryAreaId` when creating a cart with deliveryType = DELIVERY.
         */
        get: operations["DeliveryAreasDevApiController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/marketplace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the marketplace profile
         * @description Returns the profile of the marketplace resolved from the API key: slug, business category and payment configuration (pay-on-delivery, split payment).
         */
        get: operations["MarketplaceDevApiController_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DevApiErrorEnvelopeDto: {
            /** @example false */
            success: boolean;
            /**
             * @description Stable machine-readable error code. Safe to switch on in client code.
             * @example PRODUCT_NOT_FOUND
             */
            code: string;
            /**
             * @description Human-readable error message, translated when applicable.
             * @example Product not found
             */
            message: string;
            /**
             * @description Field-level validation errors, present when the error stems from input validation.
             * @example {
             *       "name": [
             *         "name should not be empty"
             *       ]
             *     }
             */
            errors?: Record<string, never>;
            /**
             * @description Contextual data attached to the error. For example, a PAYMENT_INIT_FAILED response carries the `cartPublicId` of the created cart so the payment can be retried via POST /v1/carts/{publicId}/pay.
             * @example {
             *       "cartPublicId": "CART-XPK39ZQA01"
             *     }
             */
            data?: Record<string, never>;
        };
        DevApiSuccessEnvelopeDto: {
            /** @example true */
            success: boolean;
            data: Record<string, never>;
        };
        PingPayload: {
            /** @example 42 */
            marketplaceId: number;
            /** @example 2026-05-26T13:14:15.000Z */
            timestamp: string;
        };
        DevApiPaginatedEnvelopeDto: {
            /** @example true */
            success: boolean;
            data: unknown[][];
            /**
             * @description Total rows matching the query
             * @example 42
             */
            total: number;
            /**
             * @description Index (1-based) of the first row returned
             * @example 1
             */
            start: number;
            /**
             * @description Index (1-based) of the last row returned
             * @example 10
             */
            end: number;
        };
        DevApiProductCollectionDto: {
            /** @example Fast food */
            name: string;
            /** @example fast-food */
            slug: string;
        };
        DevApiProductGalleryMediaDto: {
            /** @example 1 */
            id: number;
            /** @example https://cdn.xedoapp.com/products/gallery/abc.jpg */
            publicUrl: string;
            /**
             * @example image
             * @enum {string}
             */
            type: "image" | "video";
            /** @example Burger close-up */
            altText?: string;
        };
        DevApiProductVariationOptionDto: {
            /** @example OPT_ABC123 */
            publicId: string;
            /** @example XL */
            name: string;
            /** @example 500 */
            priceAdjustment?: number;
            /**
             * @example fixed
             * @enum {string}
             */
            priceAdjustmentType?: "fixed" | "percentage";
            galleryMedias: components["schemas"]["DevApiProductGalleryMediaDto"][];
        };
        DevApiProductVariationDto: {
            /** @example VAR_ABC123 */
            publicId: string;
            /** @example Taille */
            variationTypeName: string;
            options: components["schemas"]["DevApiProductVariationOptionDto"][];
        };
        DevApiProductCombinationDto: {
            /** @example COMB_ABC123 */
            publicId: string;
            /**
             * @description Public ids of the options forming this combination.
             * @example [
             *       "OPT_ABC123",
             *       "OPT_DEF456"
             *     ]
             */
            optionPublicIds: string[];
            /** @example 10 */
            stockQuantity: number;
            /** @example 500 */
            priceAdjustment?: number;
            /**
             * @example fixed
             * @enum {string}
             */
            priceAdjustmentType?: "fixed" | "percentage";
        };
        DevApiProductDto: {
            /** @example 6528412905 */
            publicId: string;
            /** @example Burger */
            name: string;
            /** @example burger */
            slug: string;
            /** @example 10.5 */
            price: number;
            /** @example Delicious beef burger. */
            description?: string;
            /** @example https://cdn.xedoapp.com/products/cover/abc.jpg */
            coverUrl?: string | null;
            /** @example true */
            enabled: boolean;
            collection: components["schemas"]["DevApiProductCollectionDto"];
            /**
             * Format: date-time
             * @example 2026-05-26T13:14:15.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-05-26T13:14:15.000Z
             */
            updatedAt: string;
            /** @example Nutritional information */
            productSheet?: string;
            /** @example 100 */
            stockQuantity: number;
            /** @example true */
            trackStock: boolean;
            /** @example false */
            allowBackorder: boolean;
            /** @example 10 */
            lowStockThreshold?: number | null;
            /**
             * @description Percentage paid online for split payment. Null falls back to the marketplace default.
             * @example 30
             */
            splitOnlinePaymentPercentage?: number | null;
            /** @description Product gallery (image / video). Returned on detail endpoints. */
            galleryMedias?: components["schemas"]["DevApiProductGalleryMediaDto"][];
            /** @description Variations (e.g. Size, Color) and their options. */
            variations?: components["schemas"]["DevApiProductVariationDto"][];
            /** @description Combinations (SKUs) with per-combination stock and pricing. */
            combinations?: components["schemas"]["DevApiProductCombinationDto"][];
        };
        DevApiCollectionDto: {
            /** @example 9023748120 */
            publicId: string;
            /** @example Fast food */
            name: string;
            /** @example fast-food */
            slug: string;
            /** @example Quick bites & street food. */
            description?: string;
            /** @example https://cdn.xedoapp.com/collections/cover/abc.jpg */
            coverUrl?: string | null;
            /**
             * Format: date-time
             * @example 2026-05-26T13:14:15.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-05-26T13:14:15.000Z
             */
            updatedAt: string;
        };
        DevApiOrderCustomerDto: {
            /** @example Jean */
            firstName?: string;
            /** @example Kouassi */
            lastName?: string;
            /** @example jean@example.com */
            email?: string;
            /** @example +225 07 12 34 56 78 */
            phone?: string;
        };
        DevApiOrderPaymentDto: {
            /** @example PAY-2024-001 */
            reference: string;
            /** @example 125000 */
            amount: number;
            /**
             * @description Online portion amount (split payment only).
             * @example 37500
             */
            onlineAmount?: number | null;
            /**
             * @example success
             * @enum {string}
             */
            status: "pending" | "processing" | "success" | "failed";
            /**
             * @example external_wallet
             * @enum {string}
             */
            method: "external_wallet" | "loyalty_card" | "pay_on_delivery" | "split_payment";
        };
        DevApiOrderListItemDto: {
            /**
             * @description Order internal id
             * @example 1
             */
            id: number;
            /**
             * @description Public id (cart publicId).
             * @example ORD-XPK39ZQA01
             */
            publicId: string;
            customer: components["schemas"]["DevApiOrderCustomerDto"];
            /** @example 5 */
            itemsCount: number;
            /** @example 125000 */
            orderAmount: number;
            /** @example 1000 */
            deliveryCost: number;
            payment: components["schemas"]["DevApiOrderPaymentDto"];
            /** @enum {string|null} */
            deliveryType?: "DELIVERY" | "PICKUP" | null;
            /** @enum {string|null} */
            orderStatus?: "PREPARING" | "IN_DELIVERY" | "DELIVERED" | "READY_FOR_PICKUP" | "PICKED_UP" | null;
            /**
             * @description Developer-supplied metadata attached at cart creation.
             * @example {
             *       "internalOrderId": "ORD-12345"
             *     }
             */
            meta?: Record<string, never> | null;
            /**
             * Format: date-time
             * @example 2026-05-26T13:14:15.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-05-26T13:14:15.000Z
             */
            updatedAt: string;
        };
        DevApiOrderItemCombinationDto: {
            /** @example SKU-XL-RED */
            sku: string;
            /**
             * @example [
             *       "XL",
             *       "Red"
             *     ]
             */
            optionNames: string[];
            /** @example 500 */
            priceAdjustment?: number;
            /**
             * @example fixed
             * @enum {string}
             */
            priceAdjustmentType?: "fixed" | "percentage";
        };
        DevApiOrderItemDto: {
            /**
             * @description Cart item internal id
             * @example 1
             */
            id: number;
            /** @example 283 */
            productId: number;
            /** @example Samsung Galaxy A54 */
            name: string;
            /** @example samsung-galaxy-a54 */
            slug: string;
            /** @example 125000 */
            price: number;
            /** @example 1 */
            quantity: number;
            /** @example 125000 */
            lineTotal: number;
            /** @example https://cdn.xedoapp.com/products/cover/abc.jpg */
            coverUrl?: string | null;
            /** @example COMB_ABC123 */
            combinationPublicId?: string;
            combination?: components["schemas"]["DevApiOrderItemCombinationDto"];
        };
        DevApiOrderTotalsDto: {
            /** @example 125000 */
            subtotal: number;
            /** @example 1000 */
            deliveryFees: number;
            /** @example 126000 */
            total: number;
        };
        DevApiOrderDeliveryInfoDto: {
            /** @example 1 */
            areaId: number;
            /** @example Cocody, Angré 7ème tranche */
            areaName: string;
            /** @example 1000 */
            deliveryCost: number;
        };
        DevApiOrderDeliveryDto: {
            /**
             * @example DELIVERY
             * @enum {string}
             */
            deliveryType: "DELIVERY" | "PICKUP";
            deliveryInfo?: components["schemas"]["DevApiOrderDeliveryInfoDto"] | null;
            /** @example Appeler 30 minutes avant la livraison */
            additionalDetails?: string | null;
            /**
             * @example PREPARING
             * @enum {string}
             */
            orderStatus: "PREPARING" | "IN_DELIVERY" | "DELIVERED" | "READY_FOR_PICKUP" | "PICKED_UP";
        };
        DevApiOrderDetailDto: {
            /**
             * @description Order internal id
             * @example 1
             */
            id: number;
            /** @example ORD-XPK39ZQA01 */
            publicId: string;
            /**
             * @example PAYMENT_COMPLETED
             * @enum {string}
             */
            status: "DRAFT" | "PENDING_PAYMENT" | "ABANDONED" | "PAYMENT_FAILED" | "PAYMENT_COMPLETED";
            customer: components["schemas"]["DevApiOrderCustomerDto"];
            items: components["schemas"]["DevApiOrderItemDto"][];
            totals: components["schemas"]["DevApiOrderTotalsDto"];
            payment: components["schemas"]["DevApiOrderPaymentDto"];
            delivery?: components["schemas"]["DevApiOrderDeliveryDto"] | null;
            /**
             * @description Developer-supplied metadata attached at cart creation.
             * @example {
             *       "internalOrderId": "ORD-12345"
             *     }
             */
            meta?: Record<string, never> | null;
            /**
             * Format: date-time
             * @example 2026-05-26T13:14:15.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-05-26T13:14:15.000Z
             */
            updatedAt: string;
        };
        DevApiCartCustomerDto: {
            /** @example Jean */
            firstName?: string;
            /** @example Kouassi */
            lastName?: string;
            /** @example jean@example.com */
            email?: string;
            /** @example +225 07 12 34 56 78 */
            phone?: string;
        };
        DevApiCartListItemDto: {
            /**
             * @description Cart internal id
             * @example 1
             */
            id: number;
            /** @example CART-XPK39ZQA01 */
            publicId: string;
            customer: components["schemas"]["DevApiCartCustomerDto"];
            /** @example 5 */
            itemsCount: number;
            /** @example 125000 */
            cartAmount: number;
            /** @example 1000 */
            deliveryCost: number;
            /** @enum {string} */
            status: "PENDING_PAYMENT" | "ABANDONED" | "PAYMENT_FAILED" | "PAYMENT_COMPLETED";
            /** @enum {string|null} */
            deliveryType?: "DELIVERY" | "PICKUP" | null;
            /** @enum {string|null} */
            orderStatus?: "PREPARING" | "IN_DELIVERY" | "DELIVERED" | "READY_FOR_PICKUP" | "PICKED_UP" | null;
            /**
             * @description Developer-supplied metadata attached at cart creation.
             * @example {
             *       "internalOrderId": "ORD-12345"
             *     }
             */
            meta?: Record<string, never> | null;
            /**
             * Format: date-time
             * @example 2026-05-26T13:14:15.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-05-26T13:14:15.000Z
             */
            updatedAt: string;
        };
        DevApiCartItemCombinationDto: {
            /** @example SKU-XL-RED */
            sku: string;
            /**
             * @example [
             *       "XL",
             *       "Red"
             *     ]
             */
            optionNames: string[];
            /** @example 500 */
            priceAdjustment?: number;
            /**
             * @example fixed
             * @enum {string}
             */
            priceAdjustmentType?: "fixed" | "percentage";
        };
        DevApiCartItemDto: {
            /**
             * @description Cart item internal id
             * @example 1
             */
            id: number;
            /** @example 283 */
            productId: number;
            /** @example Samsung Galaxy A54 */
            name: string;
            /** @example samsung-galaxy-a54 */
            slug: string;
            /** @example 125000 */
            price: number;
            /** @example 1 */
            quantity: number;
            /** @example 125000 */
            lineTotal: number;
            /** @example https://cdn.xedoapp.com/products/cover/abc.jpg */
            coverUrl?: string | null;
            /** @example COMB_ABC123 */
            combinationPublicId?: string;
            combination?: components["schemas"]["DevApiCartItemCombinationDto"];
        };
        DevApiCartTotalsDto: {
            /** @example 125000 */
            subtotal: number;
            /** @example 1000 */
            deliveryFees: number;
            /** @example 126000 */
            total: number;
        };
        DevApiCartDeliveryInfoDto: {
            /** @example 1 */
            areaId: number;
            /** @example Cocody, Angré 7ème tranche */
            areaName: string;
            /** @example 1000 */
            deliveryCost: number;
        };
        DevApiCartDeliveryDto: {
            /**
             * @example DELIVERY
             * @enum {string}
             */
            deliveryType: "DELIVERY" | "PICKUP";
            deliveryInfo?: components["schemas"]["DevApiCartDeliveryInfoDto"] | null;
            /** @example Appeler 30 minutes avant */
            additionalDetails?: string | null;
            /**
             * @example PREPARING
             * @enum {string}
             */
            orderStatus: "PREPARING" | "IN_DELIVERY" | "DELIVERED" | "READY_FOR_PICKUP" | "PICKED_UP";
        };
        DevApiCartDetailDto: {
            /**
             * @description Cart internal id
             * @example 1
             */
            id: number;
            /** @example CART-XPK39ZQA01 */
            publicId: string;
            /** @enum {string} */
            status: "PENDING_PAYMENT" | "ABANDONED" | "PAYMENT_FAILED" | "PAYMENT_COMPLETED";
            customer: components["schemas"]["DevApiCartCustomerDto"];
            items: components["schemas"]["DevApiCartItemDto"][];
            totals: components["schemas"]["DevApiCartTotalsDto"];
            delivery?: components["schemas"]["DevApiCartDeliveryDto"] | null;
            /**
             * @description Developer-supplied metadata attached at cart creation.
             * @example {
             *       "internalOrderId": "ORD-12345"
             *     }
             */
            meta?: Record<string, never> | null;
            /**
             * Format: date-time
             * @example 2026-05-26T13:14:15.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-05-26T13:14:15.000Z
             */
            updatedAt: string;
        };
        DevApiCheckoutPreviewResponseDto: {
            /** @example 250000 */
            subtotal: number;
            /** @example 1000 */
            deliveryCost: number;
            /** @example 251000 */
            total: number;
            /**
             * @description Set only when paymentMethod = split_payment.
             * @example 150000
             */
            onlineAmount?: number | null;
            /**
             * @description Set only when paymentMethod = split_payment.
             * @example 101000
             */
            onDeliveryAmount?: number | null;
        };
        DevApiCheckoutItemDto: {
            /** @example 9023748120 */
            publicProductId: string;
            /** @example 2 */
            quantity: number;
            /** @example COMB_ABC123 */
            combinationPublicId?: string;
        };
        DevApiCheckoutDeliveryDto: {
            /**
             * @example DELIVERY
             * @enum {string}
             */
            deliveryType: "DELIVERY" | "PICKUP";
            /**
             * @description Required when deliveryType = DELIVERY.
             * @example 1
             */
            deliveryAreaId?: number;
        };
        DevApiCheckoutPreviewDto: {
            items: components["schemas"]["DevApiCheckoutItemDto"][];
            delivery: components["schemas"]["DevApiCheckoutDeliveryDto"];
            /**
             * @example external_wallet
             * @enum {string}
             */
            paymentMethod: "external_wallet" | "split_payment";
        };
        DevApiCheckoutTotalsDto: {
            /** @example 250000 */
            subtotal: number;
            /** @example 1000 */
            deliveryCost: number;
            /** @example 251000 */
            total: number;
            /** @example 150000 */
            onlineAmount?: number | null;
            /** @example 101000 */
            onDeliveryAmount?: number | null;
        };
        DevApiCheckoutPaymentDto: {
            /** @example PAY-XPK39ZQA01 */
            reference: string;
            /** @example pending */
            status: string;
        };
        DevApiCheckoutCreateResponseDto: {
            /** @example CART-XPK39ZQA01 */
            publicId: string;
            /** @example PENDING_PAYMENT */
            status: string;
            totals: components["schemas"]["DevApiCheckoutTotalsDto"];
            payment: components["schemas"]["DevApiCheckoutPaymentDto"];
            /** @example https://checkout.moneroo.io/abc-def */
            checkoutUrl: string;
        };
        DevApiCheckoutCustomerDto: {
            /** @example Jean */
            firstName: string;
            /** @example Kouassi */
            lastName: string;
            /** @example jean@example.com */
            email: string;
            /** @example +225 07 12 34 56 78 */
            phone: string;
        };
        DevApiCheckoutCreateDto: {
            customer: components["schemas"]["DevApiCheckoutCustomerDto"];
            items: components["schemas"]["DevApiCheckoutItemDto"][];
            delivery: components["schemas"]["DevApiCheckoutDeliveryDto"];
            /**
             * @example external_wallet
             * @enum {string}
             */
            paymentMethod: "external_wallet" | "split_payment";
            /**
             * @description URL to redirect the customer to after the payment provider checkout. Must be HTTPS.
             * @example https://my-app.com/after-checkout
             */
            returnUrl: string;
            /** @example Appeler 30 min avant */
            additionalDetails?: string;
            /**
             * @description Free-form JSON payload returned as-is in every cart/order response. Use it to attach your own identifiers (e.g. internalOrderId).
             * @example {
             *       "internalOrderId": "ORD-12345",
             *       "source": "mobile-app"
             *     }
             */
            meta?: Record<string, never>;
        };
        DevApiCheckoutRetryPayResponseDto: {
            payment: components["schemas"]["DevApiCheckoutPaymentDto"];
            /** @example https://checkout.moneroo.io/abc-def */
            checkoutUrl: string;
        };
        DevApiCheckoutRetryPayDto: {
            /** @example https://my-app.com/after-checkout */
            returnUrl: string;
        };
        DevApiDeliveryAreaDto: {
            /**
             * @description Identifier to pass as `delivery.deliveryAreaId` when creating a cart.
             * @example 1
             */
            id: number;
            /** @example Cocody */
            name: string;
            /**
             * @description Delivery cost for this area.
             * @example 1000
             */
            deliveryCost: number;
        };
        DevApiBusinessCategoryDto: {
            /** @example 3 */
            id: number;
            /** @example Restauration */
            name: string;
        };
        DevApiMarketplaceProfileDto: {
            /** @example ma-boutique */
            slug: string;
            /** @example true */
            enabled: boolean;
            businessCategory?: components["schemas"]["DevApiBusinessCategoryDto"] | null;
            /** @example +225 07 12 34 56 78 */
            whatsappPhoneNumber?: string | null;
            /** @example true */
            enablePayOnDelivery: boolean;
            /** @example true */
            enableSplitPayment: boolean;
            /**
             * @description Default percentage paid online for split payment. Null if split payment is disabled.
             * @example 30
             */
            defaultOnlineSplitPaymentPercentage?: number | null;
            /**
             * @description Whether the delivery cost is paid online or on delivery in a split payment.
             * @example on_delivery
             * @enum {string}
             */
            splitPaymentDeliveryCostHandling: "online" | "on_delivery";
            /**
             * Format: date-time
             * @example 2026-05-26T13:14:15.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-05-26T13:14:15.000Z
             */
            updatedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    DevApiPingController_ping: {
        parameters: {
            query?: never;
            header: {
                /** @description Developer API key (Bearer xdk_…) */
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiSuccessEnvelopeDto"] & {
                        data?: components["schemas"]["PingPayload"];
                    };
                };
            };
            /**
             * @description Missing or invalid developer API key
             *
             *     Missing or invalid API key (`code: UNAUTHORIZED`).
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Rate limit exceeded on the burst or sustained window (`code: TOO_MANY_REQUESTS`). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Unexpected server error (`code: INTERNAL_SERVER_ERROR`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
        };
    };
    ProductsDevApiController_list: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                /** @description Column to sort by. */
                _sort?: "id" | "name" | "price" | "createdAt";
                /** @description Sort direction */
                _order?: "asc" | "desc";
                /** @description Full-text search on product name (min 3 characters). */
                search?: string;
                /** @description Filter by collection slug. */
                collection?: string;
                /** @description Include variations and combinations (SKUs) in the response. */
                includeVariations?: boolean;
                /** @description Include disabled (draft) products. Defaults to false — only enabled products are returned. */
                includeDisabled?: boolean;
            };
            header: {
                /** @description Developer API key (Bearer xdk_…) */
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiPaginatedEnvelopeDto"] & {
                        data?: components["schemas"]["DevApiProductDto"][];
                    };
                };
            };
            /**
             * @description Missing or invalid developer API key
             *
             *     Missing or invalid API key (`code: UNAUTHORIZED`).
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Rate limit exceeded on the burst or sustained window (`code: TOO_MANY_REQUESTS`). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Unexpected server error (`code: INTERNAL_SERVER_ERROR`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
        };
    };
    ProductsDevApiController_getByPublicId: {
        parameters: {
            query: {
                includeDisabled: string;
            };
            header: {
                /** @description Developer API key (Bearer xdk_…) */
                Authorization: string;
            };
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiSuccessEnvelopeDto"] & {
                        data?: components["schemas"]["DevApiProductDto"];
                    };
                };
            };
            /**
             * @description Missing or invalid developer API key
             *
             *     Missing or invalid API key (`code: UNAUTHORIZED`).
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description The requested resource does not exist (`code: NOT_FOUND`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Rate limit exceeded on the burst or sustained window (`code: TOO_MANY_REQUESTS`). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Unexpected server error (`code: INTERNAL_SERVER_ERROR`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
        };
    };
    ProductsDevApiController_getBySlug: {
        parameters: {
            query: {
                includeDisabled: string;
            };
            header: {
                /** @description Developer API key (Bearer xdk_…) */
                Authorization: string;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiSuccessEnvelopeDto"] & {
                        data?: components["schemas"]["DevApiProductDto"];
                    };
                };
            };
            /**
             * @description Missing or invalid developer API key
             *
             *     Missing or invalid API key (`code: UNAUTHORIZED`).
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description The requested resource does not exist (`code: NOT_FOUND`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Rate limit exceeded on the burst or sustained window (`code: TOO_MANY_REQUESTS`). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Unexpected server error (`code: INTERNAL_SERVER_ERROR`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
        };
    };
    CollectionsDevApiController_list: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                /** @description Column to sort by. */
                _sort?: "id" | "name" | "createdAt";
                /** @description Sort direction */
                _order?: "asc" | "desc";
                /** @description Full-text search on collection name (min 3 characters). */
                search?: string;
            };
            header: {
                /** @description Developer API key (Bearer xdk_…) */
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiPaginatedEnvelopeDto"] & {
                        data?: components["schemas"]["DevApiCollectionDto"][];
                    };
                };
            };
            /**
             * @description Missing or invalid developer API key
             *
             *     Missing or invalid API key (`code: UNAUTHORIZED`).
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Rate limit exceeded on the burst or sustained window (`code: TOO_MANY_REQUESTS`). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Unexpected server error (`code: INTERNAL_SERVER_ERROR`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
        };
    };
    CollectionsDevApiController_getByPublicId: {
        parameters: {
            query?: never;
            header: {
                /** @description Developer API key (Bearer xdk_…) */
                Authorization: string;
            };
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiSuccessEnvelopeDto"] & {
                        data?: components["schemas"]["DevApiCollectionDto"];
                    };
                };
            };
            /**
             * @description Missing or invalid developer API key
             *
             *     Missing or invalid API key (`code: UNAUTHORIZED`).
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description The requested resource does not exist (`code: NOT_FOUND`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Rate limit exceeded on the burst or sustained window (`code: TOO_MANY_REQUESTS`). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Unexpected server error (`code: INTERNAL_SERVER_ERROR`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
        };
    };
    CollectionsDevApiController_getBySlug: {
        parameters: {
            query?: never;
            header: {
                /** @description Developer API key (Bearer xdk_…) */
                Authorization: string;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiSuccessEnvelopeDto"] & {
                        data?: components["schemas"]["DevApiCollectionDto"];
                    };
                };
            };
            /**
             * @description Missing or invalid developer API key
             *
             *     Missing or invalid API key (`code: UNAUTHORIZED`).
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description The requested resource does not exist (`code: NOT_FOUND`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Rate limit exceeded on the burst or sustained window (`code: TOO_MANY_REQUESTS`). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Unexpected server error (`code: INTERNAL_SERVER_ERROR`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
        };
    };
    OrdersDevApiController_list: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                /** @description Column to sort by. */
                _sort?: "id" | "createdAt" | "amount";
                /** @description Sort direction */
                _order?: "asc" | "desc";
                /** @description Full-text search on order publicId, payment reference or customer info. */
                search?: string;
            };
            header: {
                /** @description Developer API key (Bearer xdk_…) */
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiPaginatedEnvelopeDto"] & {
                        data?: components["schemas"]["DevApiOrderListItemDto"][];
                    };
                };
            };
            /**
             * @description Missing or invalid developer API key
             *
             *     Missing or invalid API key (`code: UNAUTHORIZED`).
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Rate limit exceeded on the burst or sustained window (`code: TOO_MANY_REQUESTS`). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Unexpected server error (`code: INTERNAL_SERVER_ERROR`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
        };
    };
    OrdersDevApiController_getByPublicId: {
        parameters: {
            query?: never;
            header: {
                /** @description Developer API key (Bearer xdk_…) */
                Authorization: string;
            };
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiSuccessEnvelopeDto"] & {
                        data?: components["schemas"]["DevApiOrderDetailDto"];
                    };
                };
            };
            /**
             * @description Missing or invalid developer API key
             *
             *     Missing or invalid API key (`code: UNAUTHORIZED`).
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description The requested resource does not exist (`code: NOT_FOUND`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Rate limit exceeded on the burst or sustained window (`code: TOO_MANY_REQUESTS`). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Unexpected server error (`code: INTERNAL_SERVER_ERROR`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
        };
    };
    OrdersDevApiController_getInvoice: {
        parameters: {
            query?: never;
            header: {
                /** @description Developer API key (Bearer xdk_…) */
                Authorization: string;
            };
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Missing or invalid developer API key
             *
             *     Missing or invalid API key (`code: UNAUTHORIZED`).
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description The requested resource does not exist (`code: NOT_FOUND`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Rate limit exceeded on the burst or sustained window (`code: TOO_MANY_REQUESTS`). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Unexpected server error (`code: INTERNAL_SERVER_ERROR`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
        };
    };
    CartsDevApiController_list: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                /** @description Column to sort by. */
                _sort?: "id" | "createdAt";
                /** @description Sort direction */
                _order?: "asc" | "desc";
                /** @description Full-text search on cart publicId or customer info. */
                search?: string;
            };
            header: {
                /** @description Developer API key (Bearer xdk_…) */
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiPaginatedEnvelopeDto"] & {
                        data?: components["schemas"]["DevApiCartListItemDto"][];
                    };
                };
            };
            /**
             * @description Missing or invalid developer API key
             *
             *     Missing or invalid API key (`code: UNAUTHORIZED`).
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Rate limit exceeded on the burst or sustained window (`code: TOO_MANY_REQUESTS`). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Unexpected server error (`code: INTERNAL_SERVER_ERROR`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
        };
    };
    CheckoutDevApiController_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Developer API key (Bearer xdk_…) */
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevApiCheckoutCreateDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiSuccessEnvelopeDto"] & {
                        data?: components["schemas"]["DevApiCheckoutCreateResponseDto"];
                    };
                };
            };
            /** @description Invalid request — malformed parameters or body (`code: BAD_REQUEST`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /**
             * @description Missing or invalid developer API key
             *
             *     Missing or invalid API key (`code: UNAUTHORIZED`).
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description The requested resource does not exist (`code: NOT_FOUND`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description The request is well-formed but cannot be processed (`code: UNPROCESSABLE_ENTITY`). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Rate limit exceeded on the burst or sustained window (`code: TOO_MANY_REQUESTS`). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Unexpected server error (`code: INTERNAL_SERVER_ERROR`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description The payment provider could not be reached (`code: PAYMENT_INIT_FAILED`). `data.cartPublicId` carries the created cart so the payment can be retried. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
        };
    };
    CartsDevApiController_getByPublicId: {
        parameters: {
            query?: never;
            header: {
                /** @description Developer API key (Bearer xdk_…) */
                Authorization: string;
            };
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiSuccessEnvelopeDto"] & {
                        data?: components["schemas"]["DevApiCartDetailDto"];
                    };
                };
            };
            /**
             * @description Missing or invalid developer API key
             *
             *     Missing or invalid API key (`code: UNAUTHORIZED`).
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description The requested resource does not exist (`code: NOT_FOUND`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Rate limit exceeded on the burst or sustained window (`code: TOO_MANY_REQUESTS`). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Unexpected server error (`code: INTERNAL_SERVER_ERROR`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
        };
    };
    CheckoutDevApiController_preview: {
        parameters: {
            query?: never;
            header: {
                /** @description Developer API key (Bearer xdk_…) */
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevApiCheckoutPreviewDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiSuccessEnvelopeDto"] & {
                        data?: components["schemas"]["DevApiCheckoutPreviewResponseDto"];
                    };
                };
            };
            /** @description Invalid request — malformed parameters or body (`code: BAD_REQUEST`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /**
             * @description Missing or invalid developer API key
             *
             *     Missing or invalid API key (`code: UNAUTHORIZED`).
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description The requested resource does not exist (`code: NOT_FOUND`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description The request is well-formed but cannot be processed (`code: UNPROCESSABLE_ENTITY`). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Rate limit exceeded on the burst or sustained window (`code: TOO_MANY_REQUESTS`). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Unexpected server error (`code: INTERNAL_SERVER_ERROR`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
        };
    };
    CheckoutDevApiController_retryPay: {
        parameters: {
            query?: never;
            header: {
                /** @description Developer API key (Bearer xdk_…) */
                Authorization: string;
            };
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevApiCheckoutRetryPayDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiSuccessEnvelopeDto"] & {
                        data?: components["schemas"]["DevApiCheckoutRetryPayResponseDto"];
                    };
                };
            };
            /**
             * @description Missing or invalid developer API key
             *
             *     Missing or invalid API key (`code: UNAUTHORIZED`).
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description The requested resource does not exist (`code: NOT_FOUND`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description The request is well-formed but cannot be processed (`code: UNPROCESSABLE_ENTITY`). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Rate limit exceeded on the burst or sustained window (`code: TOO_MANY_REQUESTS`). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Unexpected server error (`code: INTERNAL_SERVER_ERROR`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description The payment provider could not be reached (`code: PAYMENT_INIT_FAILED`). `data.cartPublicId` carries the created cart so the payment can be retried. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
        };
    };
    DeliveryAreasDevApiController_list: {
        parameters: {
            query?: never;
            header: {
                /** @description Developer API key (Bearer xdk_…) */
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiSuccessEnvelopeDto"] & {
                        data?: components["schemas"]["DevApiDeliveryAreaDto"][];
                    };
                };
            };
            /**
             * @description Missing or invalid developer API key
             *
             *     Missing or invalid API key (`code: UNAUTHORIZED`).
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Rate limit exceeded on the burst or sustained window (`code: TOO_MANY_REQUESTS`). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Unexpected server error (`code: INTERNAL_SERVER_ERROR`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
        };
    };
    MarketplaceDevApiController_getProfile: {
        parameters: {
            query?: never;
            header: {
                /** @description Developer API key (Bearer xdk_…) */
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiSuccessEnvelopeDto"] & {
                        data?: components["schemas"]["DevApiMarketplaceProfileDto"];
                    };
                };
            };
            /**
             * @description Missing or invalid developer API key
             *
             *     Missing or invalid API key (`code: UNAUTHORIZED`).
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description The requested resource does not exist (`code: NOT_FOUND`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Rate limit exceeded on the burst or sustained window (`code: TOO_MANY_REQUESTS`). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
            /** @description Unexpected server error (`code: INTERNAL_SERVER_ERROR`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevApiErrorEnvelopeDto"];
                };
            };
        };
    };
}
