export { Xedo, type XedoOptions } from './client';
export type { FetchLike } from './transport';

export {
  XedoError,
  XedoAuthError,
  XedoValidationError,
  XedoNotFoundError,
  XedoStockError,
  XedoConflictError,
  XedoRateLimitError,
  XedoPaymentInitError,
  XedoConnectionError,
  type XedoErrorParams,
} from './errors';

export type {
  JsonObject,
  SortOrder,
  // Enums
  OrderStatus,
  CartStatus,
  FulfillmentStatus,
  DeliveryType,
  PaymentStatus,
  OrderPaymentMethod,
  PriceAdjustmentType,
  MediaType,
  // Entities
  PingResult,
  Product,
  ProductCollection,
  ProductGalleryMedia,
  ProductVariation,
  ProductVariationOption,
  ProductCombination,
  Collection,
  Order,
  OrderListItem,
  OrderCustomer,
  OrderPayment,
  OrderItem,
  OrderTotals,
  OrderDelivery,
  Cart,
  CartListItem,
  CartCustomer,
  CartItem,
  CartTotals,
  CartDelivery,
  CheckoutPreview,
  CheckoutTotals,
  CheckoutPayment,
  CheckoutResult,
  CheckoutRetryResult,
  DeliveryArea,
  BusinessCategory,
  MarketplaceProfile,
  // List / request params
  ListParams,
  ProductListParams,
  CollectionListParams,
  OrderListParams,
  CartListParams,
  RetrieveOptions,
  RequestOptions,
  PaginatedResult,
  RateLimitInfo,
  // Checkout inputs
  CheckoutItem,
  CheckoutDelivery,
  CheckoutCustomer,
  PaymentMethod,
  CheckoutPreviewInput,
  CheckoutCreateInput,
  CheckoutRetryPayInput,
} from './types/public';
